---
title: "Activities"
editor: visual
---

## Voluntary engagement

**"International Viadrina Ambassador" of the European University Viadrina**<br> Frankfurt (Oder), Germany \| 16.11.2021 - present<br> As Viadrina Ambassador:<br> - Organization and execution of informational events in schools and universities in Yerevan

**"Unicef" University Group Frankfurt (Oder) of the European University Viadrina**<br> Frankfurt (Oder), Germany \| 01.10.2020 - 30.09.2021<br> As Finance Chair:<br> - Project management and leadership<br> - Project coordination for UNICEF at the university<br> - Organization and structuring of projects<br> - Representation of UNICEF at the university

**"Unicef" University Group Frankfurt (Oder) of the European University Viadrina**<br> Frankfurt (Oder), Germany \| 01.10.2019 - 30.09.2020<br> As a permanent member:<br> - Participation in the organization of fundraising campaigns, events, and projects

**"Armenian-German and International Cultural Center (ADIK) e.V."**<br> Berlin, Germany \| 09.2019 - present<br> As a permanent member:<br> - Coordination of intercultural projects to promote cultural exchange between AM and DE.<br> - Public relations for ADIK e.V. through content creation and social media usage.<br> - Active participation in discussions and decision-making processes to achieve the goals and visions.<br>

**"ARNAP" National Platform for Disaster Risk Reduction**<br> Yerevan, Armenia \| 02.2018 - 05.2019<br> As a permanent member:<br> - Participation in events and work meetings

## Awards

**Friedrich Ebert Stiftung**<br> Frankfurt (Oder), Germany \| 01.05.2024 - present<br> - Recipient of the Friedrich Ebert Stiftung scholarship, recognizing academic excellence and leadership potential.

**Deutschlandstipendium**<br> Frankfurt (Oder), Germany \| 01.10.2019 - 30.09.2020<br> - Awarded by Mebus-Pleuger Stipendienstiftung & Stiftung Europa-Universität for outstanding academic performance and social engagement.

**Deutsches Sprachdiplom - Zweite Stufe (DSDII)**<br> Yerevan, Armenia \| 15.04.2019<br> - Achieved the C1 level certification in German language proficiency, demonstrating advanced competency in the language.

**PAD (Internationales Preisträgerprogramm)**<br> Köln, Bonn, München, Berlin, Germany \| 23.06.2018 - 22.07.2018<br> - Participated in this prestigious international award program, enhancing language skills and cultural understanding.

## Language Skills

-   Armenian (Native)<br>
-   German (C1 level)<br>
-   English (C1 level)<br>
-   Russian (B2 level)<br>
-   French (A1 level)<br>
